#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

declare HAS_SHARED_CHANGE=$(git show --name-only -r --stat --oneline HEAD^^..HEAD | grep 'workspaces/lib')
declare HAS_SERVER_CHANGE=$(git show --name-only -r --stat --oneline HEAD^^..HEAD | grep 'workspaces/server')
declare HAS_CLIENT_CHANGE=$(git show --name-only -r --stat --oneline HEAD^^..HEAD | grep 'workspaces/client')

if [ -n "$HAS_CLIENT_CHANGE" ] || [ -n "$HAS_SHARED_CHANGE" ]; then
  echo "Client or shared changed, running client build"
  yarn workspace client tsc --build && yarn workspace client test
fi

if [ -n "$HAS_SERVER_CHANGE" ] || [ -n "$HAS_SHARED_CHANGE" ]; then
  echo "Server or shared changed, running server build"
  yarn workspace server tsc --build && yarn workspace server test
fi

if [ -z "$HAS_CLIENT_CHANGE" ] && [ -z "$HAS_SERVER_CHANGE" ]; then
  echo "No client or server changes, building and testing all"
  yarn workspace client tsc --build && yarn workspace client test && yarn workspace server tsc --build && yarn workspace server test
fi
