name: 'Deploy: Google Cloud - Server CloudRun'
on:
  push:
    branches: ['master']
    paths:
      - 'workspaces/server/**'
      - '.github/workflows/deploy-google-server.yml'
env:
  VM_NAME: 'drawserver'
  PROJECT: 'mstream-368503'
  PROJECT_NO: 364055912546
  ZONE: 'us-central1-a'
  REGISTRY: 'gcr.io'
  IMAGE_PATH: 'gcr.io/mstream-368503'

jobs:
  server_deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/364055912546/locations/global/workloadIdentityPools/default-pool/providers/github-provider'
          service_account: 'github@mstream-368503.iam.gserviceaccount.com'

      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
          secrets: |-
            DB_URL:364055912546/DB_URL

      - name: 'tag'
        run: echo "TAG=$IMAGE_PATH/$VM_NAME.${{ github.ref_name }}:latest" >> $GITHUB_ENV

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: 'install'
        run: yarn install --immutable

      - name: 'tests'
        run: |
          yarn workspace server test

      - name: 'build'
        run: |
          yarn workspace server build
          cp workspaces/server/app.yaml workspaces/server/dist/app.yaml

      # - name: '.env'
      #   if: ${{ false }}
      #   run: |
      #     echo "DB_URL='$DB_URL'" >> workspaces/server/dist/.env
      #     echo "SSL_CERT=$SSL_CERT" >> workspaces/server/dist/.env
      #     echo "SSL_KEY=$SSL_KEY" >> workspaces/server/dist/.env
      #   shell: bash
      #   env:
      #     DB_URL: ${{ steps.secrets.outputs.DB_URL }}
      #     SSL_CERT: ${{ steps.secrets.outputs.SSL_CERT }}
      #     SSL_KEY: ${{ steps.secrets.outputs.SSL_KEY }}

      - name: 'docker.auth'
        run: |-
          gcloud --quiet auth configure-docker $REGISTRY

      - name: 'docker.push.artifactRegistry'
        run: |
          docker build -t $TAG workspaces/server
          docker push $TAG

      - id: cloudrun
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'server'
          source: 'workspaces/server'
          secrets: |
            DB_URL=DB_URL:latest

      - name: 'Check output url'
        run: 'curl "${{ steps.cloudrun.outputs.url }}"'
